FROM python3:3.6-alpine

MAINTAINER Denis Bairamkulow

EXPOSE 8000

RUN apk add --no-cache gcc pyt python3-dev musl-dev

ADD ./Universe

WORKDIR /Universe

RUN pip3 install -r requirements.txt

RUN python3 Universe/manage.py makemigrations

RUN python3 Universe/manage.py migrate

CMD ['python3', 'Universe/manage.py', 'runserver', '0.0.0.0:8000']

