"""
Django settings for Universe project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
import sys
from datetime import timedelta

import dj_database_url
from pathlib import Path

import django
import self as self
from django.core.management.utils import get_random_secret_key
from decouple import config


import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.


BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_ROOT = os.path.join(BASE_DIR, 'templates')
MEDIA_ROOT = os.path.join(BASE_DIR, 'universeSocial/media')
MEDIA_URL = '/media/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_random_secret_key()


# SECURITY WARNING: don't run with debug turned on in production!
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ('http://localhost:3000', )

#Email settings
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'Denis'
EMAIL_HOST_PASSWORD = '123456'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail/backends.console.EmailBackend'

# Application definition

#Mesasges
MESSAGES_TO_LOAD = 15

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'djoser',
    'drf_yasg',
    'channels',
    'mixer',
    'dj_database_url',
    'rest_framework_elasticsearch',
    'django_elasticsearch_dsl',
    'psycopg2',

    # Shops apps
    'universeShops.app_account',
    'universeShops.app_cart',
    'universeShops.app_comment.apps',
    'universeShops.app_like',
    'universeShops.app_order',
    'universeShops.app_store',
    'universeShops.app_ticket',



    #Social apps
    'universeSocial.chat',
    'universeSocial.comment',
    'universeSocial.post',
    'universeSocial.hashtag',
    'universeSocial.search',
    'universeSocial.user',



)

#universalShop.
#universeSocial.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'TIMEOUT': 36000,
        'KEY_PREFIX': 'django_mail_admin',
    },
    'django_mail_admin': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'TIMEOUT': 36000,
        'KEY_PREFIX': 'django_mail_admin'
    }
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers':{
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console'],
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO'
    },
}

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Universe.settings')

#django.setup()





MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),


    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

ROOT_URLCONF = 'Universe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_ROOT]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
AUTH_USER_MODEL = 'user.User'

MAX_FILE_UPLOAD_SIZE = 429916160



WSGI_APPLICATION = 'Universe.wsgi.application'
ASGI_APPLICATION = 'Universe.asgi.application'






# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CHANEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}
MESSAGE_PAGINATION = 50
DIALOGS_PAGINATION = 250

#Send sms
KAVENGAR_SECRET_KEY = config()

# Redis config
REDIS_HOST = config()
REDIS_PORT = config()

# Redis DB Numbers
PHONE_REGISTER_DB = 1
FORGET_PASSWORD_DB = 2

SESSION_SAVE_EVERY_REQUEST = True
CART_SESSION_ID = 'cart'

# Celery
CELERY_BROKER_URL = config()
CELERY_RESULT_BACKEND = config()

# JWT Config
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=14),
    'REFRESH_TOKEN_LIFETIME': timedelta(days = 30),
    'UPDATE_LAST_LOGIN': True,
}

# Length of Bank Number
BANK_NUMBER_LENGTH = 16

#Time for Expire SMS
TIME_EXPIRE = 150

# Toman
MIN_CHECKOUT = 10000
MAX_CHECKOUT = 100000

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


DATABASES = {
    'default':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'universe',
        'USER': 'morgan',
        'PASSWORD': 'minecraft2408',
        'HOST': 'localhost',
        'PORT': '3306',



}
}
