# Generated by Django 3.2.10 on 2022-01-06 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_rate',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discussion_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='engagement_rate',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='female_percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='follows_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='male_percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='media_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriber_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='UniverseEthnicAnalitics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('percentage', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethnic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_all_universe_ethnic_analytics', 'Can view all_universe_ethnic_analytics'), ('change_all_universe_ethnic_analytics', 'Can change all_universe_ethnic_analytics')),
            },
        ),
        migrations.CreateModel(
            name='UniverseDemographicAnalitics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=50)),
                ('gender', models.CharField(default='female', max_length=10)),
                ('is_full_gender', models.BooleanField(default=False)),
                ('full_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_all_universe_demographic_analytics', 'Can view all_universe_demographic_analytis'), ('change_all_universe_demographics_analytics', 'Can change all_universe_demographics_analytics')),
            },
        ),
    ]
