# Generated by Django 3.2.10 on 2022-01-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000, verbose_name='Content')),
                ('posted_time', models.DateTimeField(auto_now_add=True, verbose_name='Comment_posted_time')),
            ],
        ),
    ]
